"""
하이브 쿼리에 파라미터 입력 자동화를 위한 스크립트

사용법
- sql 파일
  - 파라미터가 들어갈 부분을 $[PARAM_NAME] 형태로 지정
  - ex) SELECT * FROM $[TB_NAME];
  
- 스크립트 실행
  - cat (입력 sql 파일) | python formmater.py --params (파라미터명)=(파라미터값) > (생성된 sql 파일)
  - ex) cat example.template.sql | python formmater.py --params TB_NAME=test_table > example_test.sql

"""

import re
import os
from optparse import OptionParser
from functools import reduce

if __name__ == "__main__":
    yesterday = datetime.datetime.today() - datetime.timedelta( days=1 )
    parser = OptionParser()
    parser.add_option( "--params", action="append", dest="params")
    options, args = parser.parse_args()

    print('-- generated by formatter')

    if (options.params is not None) and (len(options.params)) > 0:
        print('-- params : ', reduce(lambda p1, p2: p2 if p1 == "" else p1 + ", " + p2, options.params, ""))
        params = {k: v for k, v in map(lambda x: x.split("="), options.params)}
    else:
        print('-- params : {}')
        params = dict()


    ###########
    param_pattern = re.compile( '\$\[(.*?)\]' )


    for line in sys.stdin:
        for block in set(param_pattern.findall( line )):
            line = line.replace( '$[%s]' % block, str(params[block]))

        line.replace("\n", "")
        print(line)
